### PR TITLE
Deps - bump esbuild to latest

### PR DESCRIPTION
**Pull request by Darkle**
At the moment I am unable to install `esbuild-plugin-glob` with the latest esbuild installed. npm gives the following error message:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: roffline@0.1.0
npm ERR! Found: esbuild@0.13.2
npm ERR! node_modules/esbuild
npm ERR!   dev esbuild@"^0.13.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"^0.12.14" from esbuild-plugin-glob@1.0.1
npm ERR! node_modules/esbuild-plugin-glob
npm ERR!   esbuild-plugin-glob@"^1.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/coop/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coop/.npm/_logs/2021-09-28T08_40_44_615Z-debug.log
```
This pr updates esbuilt to the latest version in the dependencies.

### CODE REVIEW

**Comment by waspeer** [comment]
Aah bummer. I’ll take a look at this asap!

-Wannes

**Comment by waspeer** [comment]
Should be fixed now. I thought the caret (^) indicated that minor changes are fine right? Do you have any idea why this broke?

**Comment by Darkle** [comment]
> Do you have any idea why this broke?

Based on [this confusing page](https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json), it seems that the tilde constraint works a little differently when the version is below 1.

[This package](https://github.com/npm/node-semver#versions) seems to be what npm uses for checking the version constraints, and based on the readme, perhaps this might be appropriate: `0.x.x` ? I'm not 100% certain though.

It seems to work ok here (though it does give a warning):
Old version: https://jubianchi.github.io/semver-check/#/~0.12.14/0.13.0
New version: https://jubianchi.github.io/semver-check/#/0.x.x/0.13.0

**Comment by waspeer** [comment]
Nice one! I changed it to `0.x.x`. Thanks!

**Pull request merged**
